name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main # or your default branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18 # or your preferred Node.js version
          cache: npm # or npm, pnpm, bun

      - name: Install dependencies
        run: npm ci --frozen-lockfile # or npm ci, pnpm install, bun install

      - name: Build Docusaurus website
        run: npm run build # or npm run build, pnpm build, bun build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
